### ISSUE TITLE
Fatal error: Call to a member function getPurchasableEntityTypeId() on null

### ISSUE THREAD

**Issue by jpdaut** [mglaman/commerce_demo#10]
Hi
With the latest code, I get an error when clicking any product right after install and running migration:

Fatal error: Call to a member function getPurchasableEntityTypeId() on null in /home/ss4/cdemo/web/modules/contrib/commerce/modules/order/src/Entity/OrderItem.php on line 306

**Comment by mglaman** [comment]
This is with a fresh clone? I noticed this, too and it was due to the config being incorrect. It should have been fixed. I will review.

**Comment by jpdaut** [comment]
Yes, a fresh clone.  I just do like in your Installation notes : add commerce_demo to the repositories in composer.json, then:

composer require drupal/commerce_demo:dev-master
cd web
drush en commerce_demo -y
drush migrate-import --all

Right after that, Cart is not enabled yet, and you can view products normally.  Everything is fine.  But if you enable Cart, you get the error, getPurchasableEntityTypeId() on null, when trying to view a product.

**Comment by mglaman** [comment]
Okay, I'll double check. The issue was config had "lineItemType" not "orderItemType" https://github.com/mglaman/commerce_demo/blob/master/config/install/commerce_product.commerce_product_variation_type.t_shirt.yml#L6

But I'll run fresh again

**Comment by jpdaut** [comment]
I don't see that it had lineItemType before..

It's orderItemType now, but the problem remains : view a product w/add to cart, get the getPurchasableEntityTypeId error. 

Thank you for checking this out.

**Comment by jpdaut** [comment]
I do see now that you had lineItemType before, and you corrected it 3 days ago. 

However the latest commit has orderItemType, and the getPurchasableEntityTypeId error.

**Comment by mglaman** [comment]
This should be fixed all around, now.
